[package]
name = "crab_hop"
version = "0.1.0"
edition = "2021"

[lib]
name = "crab_hop"
path = "src/lib/lib.rs"

[[bin]]
name = "cli"
path = "src/bin/cli/app.rs"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
mockall = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.12"
